version: "3.0"

services:
  nolt-customer-orders:
    image: nolt-customer-orders-ms
    build:
      context: ..
      dockerfile: ./nolt-customer-orders/Dockerfile
    ports:
      - "9001:9001"
    environment:
      kafka_bootstrap_servers: 'broker:29092'

  nolt-restaurant-orders:
    image: nolt-restaurant-orders-ms
    build:
      context: ..
      dockerfile: ./nolt-restaurant-orders/Dockerfile
    ports:
      - "9002:9002"
    environment:
      kafka_bootstrap_servers: 'broker:29092'